In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/Occupancy_Estimation.csv")

In [3]:
df.head()

,Date,Time,S1_Temp,S2_Temp,S3_Temp,S4_Temp,S1_Light,S2_Light,S3_Light,S4_Light,S1_Sound,S2_Sound,S3_Sound,S4_Sound,S5_CO2,S5_CO2_Slope,S6_PIR,S7_PIR,Room_Occupancy_Count
0,2017/12/22,10:49:41,24.94,24.75,24.56,25.38,121,34,53,40,0.08,0.19,0.06,0.06,390,0.769231,0,0,1
1,2017/12/22,10:50:12,24.94,24.75,24.56,25.44,121,33,53,40,0.93,0.05,0.06,0.06,390,0.646154,0,0,1
2,2017/12/22,10:50:42,25.00,24.75,24.50,25.44,121,34,53,40,0.43,0.11,0.08,0.06,390,0.519231,0,0,1
3,2017/12/22,10:51:13,25.00,24.75,24.56,25.44,121,34,53,40,0.41,0.10,0.10,0.09,390,0.388462,0,0,1
4,2017/12/22,10:51:44,25.00,24.75,24.56,25.44,121,34,54,40,0.18,0.06,0.06,0.06,390,0.253846,0,0,1

In [4]:
df.shape

(10129, 19)

In [5]:
df.columns.tolist()

['Date',
 'Time',
 'S1_Temp',
 'S2_Temp',
 'S3_Temp',
 'S4_Temp',
 'S1_Light',
 'S2_Light',
 'S3_Light',
 'S4_Light',
 'S1_Sound',
 'S2_Sound',
 'S3_Sound',
 'S4_Sound',
 'S5_CO2',
 'S5_CO2_Slope',
 'S6_PIR',
 'S7_PIR',
 'Room_Occupancy_Count']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10129 entries, 0 to 10128
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  10129 non-null  str
 1   Time                  10129 non-null  str
 2   S1_Temp               10129 non-null  float64
 3   S2_Temp               10129 non-null  float64
 4   S3_Temp               10129 non-null  float64
 5   S4_Temp               10129 non-null  float64
 6   S1_Light              10129 non-null  int64
 7   S2_Light              10129 non-null  int64
 8   S3_Light              10129 non-null  int64
 9   S4_Light              10129 non-null  int64
 10  S1_Sound              10129 non-null  float64
 11  S2_Sound              10129 non-null  float64
 12  S3_Sound              10129 non-null  float64
 13  S4_Sound              10129 non-null  float64
 14  S5_CO2                10129 non-null  int64
 15  S5_CO2_Slope          10129 non-null  float64
 16  S6_PIR                10129 non-null  int64
 17  S7_PIR                10129 non-null  int64
 18  Room_Occupancy_Count  10129 non-null  int64
dtypes: float64(9), int64(8), str(2)
memory usage: 1.5 MB

In [7]:
df.isnull().sum()

Date                    0
Time                    0
S1_Temp                 0
S2_Temp                 0
S3_Temp                 0
S4_Temp                 0
S1_Light                0
S2_Light                0
S3_Light                0
S4_Light                0
S1_Sound                0
S2_Sound                0
S3_Sound                0
S4_Sound                0
S5_CO2                  0
S5_CO2_Slope            0
S6_PIR                  0
S7_PIR                  0
Room_Occupancy_Count    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["Room_Occupancy_Count"].value_counts().sort_index()

Room_Occupancy_Count
0    8228
1     459
2     748
3     694
Name: count, dtype: int64

In [10]:
df[["S6_PIR", "S7_PIR"]].value_counts()

S6_PIR  S7_PIR
0       0         8931
1       1          521
        0          392
0       1          285
Name: count, dtype: int64

In [11]:
df[["S6_PIR", "S7_PIR"]].describe()

             S6_PIR        S7_PIR
count  10129.000000  10129.000000
mean       0.090137      0.079574
std        0.286392      0.270645
min        0.000000      0.000000
25%        0.000000      0.000000
50%        0.000000      0.000000
75%        0.000000      0.000000
max        1.000000      1.000000

In [12]:
df[
    [
        "S1_Temp", "S2_Temp", "S3_Temp", "S4_Temp",
        "S1_Light", "S2_Light", "S3_Light", "S4_Light"
    ]
].describe()

,S1_Temp,S2_Temp,S3_Temp,S4_Temp,S1_Light,S2_Light,S3_Light,S4_Light
count,10129.000000,10129.000000,10129.000000,10129.000000,10129.000000,10129.00000,10129.000000,10129.000000
mean,25.454012,25.546059,25.056621,25.754125,25.445059,26.01629,34.248494,13.220259
std,0.351351,0.586325,0.427283,0.356434,51.011264,67.30417,58.400744,19.602219
min,24.940000,24.750000,24.440000,24.940000,0.000000,0.00000,0.000000,0.000000
25%,25.190000,25.190000,24.690000,25.440000,0.000000,0.00000,0.000000,0.000000
50%,25.380000,25.380000,24.940000,25.750000,0.000000,0.00000,0.000000,0.000000
75%,25.630000,25.630000,25.380000,26.000000,12.000000,14.00000,50.000000,22.000000
max,26.380000,29.000000,26.190000,26.560000,165.000000,258.00000,280.000000,74.000000

In [24]:
df["Avg_Temperature"] = df[
    ["S1_Temp", "S2_Temp", "S3_Temp", "S4_Temp"]
].mean(axis=1)

In [25]:
df["Avg_Light"] = df[
    ["S1_Light", "S2_Light", "S3_Light", "S4_Light"]
].mean(axis=1)

In [26]:
df["PIR_Motion"] = (
    (df["S6_PIR"] == 1) |
    (df["S7_PIR"] == 1)
).astype(int)

In [27]:
df["Occupied"] = (
    df["Room_Occupancy_Count"] > 0
).astype(int)

In [28]:
df[
    [
        "Avg_Temperature",
        "Avg_Light",
        "PIR_Motion",
        "Room_Occupancy_Count",
        "Occupied"
    ]
].head(10)

   Avg_Temperature  Avg_Light  PIR_Motion  Room_Occupancy_Count  Occupied
0          24.9075      62.00           0                     1         1
1          24.9225      61.75           0                     1         1
2          24.9225      62.00           0                     1         1
3          24.9375      62.00           0                     1         1
4          24.9375      62.25           0                     1         1
5          24.9525      62.25           0                     1         1
6          24.9375      62.00           1                     1         1
7          24.9525      62.50           0                     1         1
8          24.9675      64.00           0                     1         1
9          24.9675      58.75           1                     1         1

In [19]:
df[
    [
        "Avg_Temperature",
        "Avg_Light",
        "PIR_Motion",
        "Occupied"
    ]
].describe()

       Avg_Temperature     Avg_Light    PIR_Motion      Occupied
count     10129.000000  10129.000000  10129.000000  10129.000000
mean         25.452704     24.732525      0.118274      0.187679
std           0.399201     43.811460      0.322949      0.390475
min          24.890000      0.000000      0.000000      0.000000
25%          25.127500      0.000000      0.000000      0.000000
50%          25.362500      0.000000      0.000000      0.000000
75%          25.612500     30.500000      0.000000      0.000000
max          26.800000    193.750000      1.000000      1.000000

In [20]:
df["PIR_Motion"].value_counts()

PIR_Motion
0    8931
1    1198
Name: count, dtype: int64

In [21]:
df[
    [
        "Avg_Temperature",
        "Avg_Light",
        "PIR_Motion",
        "Occupied"
    ]
].corr()["Occupied"].sort_values(ascending=False)

Occupied           1.000000
Avg_Light          0.838022
PIR_Motion         0.743173
Avg_Temperature    0.670177
Name: Occupied, dtype: float64

In [22]:
ml_data = df[
    [
        "Avg_Temperature",
        "Avg_Light",
        "PIR_Motion",
        "Occupied"
    ]
].copy()

In [23]:
ml_data.head()

   Avg_Temperature  Avg_Light  PIR_Motion  Occupied
0          24.9075      62.00           0         1
1          24.9225      61.75           0         1
2          24.9225      62.00           0         1
3          24.9375      62.00           0         1
4          24.9375      62.25           0         1

In [29]:
ml_data = df[
    [
        "Avg_Temperature",
        "Avg_Light",
        "PIR_Motion",
        "Occupied"
    ]
].copy()

In [30]:
ml_data.head(10)

   Avg_Temperature  Avg_Light  PIR_Motion  Occupied
0          24.9075      62.00           0         1
1          24.9225      61.75           0         1
2          24.9225      62.00           0         1
3          24.9375      62.00           0         1
4          24.9375      62.25           0         1
5          24.9525      62.25           0         1
6          24.9375      62.00           1         1
7          24.9525      62.50           0         1
8          24.9675      64.00           0         1
9          24.9675      58.75           1         1

In [31]:
ml_data.shape

(10129, 4)

In [32]:
ml_data.isnull().sum()

Avg_Temperature    0
Avg_Light          0
PIR_Motion         0
Occupied           0
dtype: int64

In [33]:
ml_data["Occupied"].value_counts()

Occupied
0    8228
1    1901
Name: count, dtype: int64

In [34]:
ml_data["Occupied"].value_counts(normalize=True) * 100

Occupied
0    81.232106
1    18.767894
Name: proportion, dtype: float64

In [35]:
ml_data.to_csv("../data/occupancy_ml_dataset.csv", index=False)

In [36]:
ml_data.head()

   Avg_Temperature  Avg_Light  PIR_Motion  Occupied
0          24.9075      62.00           0         1
1          24.9225      61.75           0         1
2          24.9225      62.00           0         1
3          24.9375      62.00           0         1
4          24.9375      62.25           0         1

In [37]:
ml_data.shape

(10129, 4)

In [38]:
ml_data.isnull().sum()

Avg_Temperature    0
Avg_Light          0
PIR_Motion         0
Occupied           0
dtype: int64

In [39]:
ml_data["Occupied"].value_counts()

Occupied
0    8228
1    1901
Name: count, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X = ml_data[
    [
        "Avg_Temperature",
        "Avg_Light",
        "PIR_Motion"
    ]
]

y = ml_data["Occupied"]

In [42]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [43]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (8103, 3)
X_test : (2026, 3)
y_train: (8103,)
y_test : (2026,)

In [44]:
print("Training distribution:")
print(y_train.value_counts())

print("\nTesting distribution:")
print(y_test.value_counts())

Training distribution:
Occupied
0    6582
1    1521
Name: count, dtype: int64

Testing distribution:
Occupied
0    1646
1     380
Name: count, dtype: int64

In [47]:
## Now: Train Our First ML Model

In [48]:
## Import Logistic Regression

In [49]:
from sklearn.linear_model import LogisticRegression

In [52]:
model_lr = LogisticRegression(
    random_state=42,
    max_iter=1000
)

In [53]:
model_lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [54]:
y_pred_lr = model_lr.predict(X_test)

In [55]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [56]:
print("Accuracy:", accuracy_score(y_test, y_pred_lr))

Accuracy: 0.9901283316880553

In [57]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1646
           1       0.98      0.96      0.97       380

    accuracy                           0.99      2026
   macro avg       0.99      0.98      0.98      2026
weighted avg       0.99      0.99      0.99      2026

In [61]:
#Confusion Matrix

In [62]:
cm_lr = confusion_matrix(y_test, y_pred_lr)

print(cm_lr)

[[1640    6]
 [  14  366]]